/**
 * Turn a ComfyUI API-format workflow into a contract the model can read.
 * Closed slot types; open workflow set. Never put the graph JSON in model context.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

const SLOT_TYPES = new Set(['text', 'number', 'seed', 'model', 'lora', 'image', 'video', 'audio'])

const IGNORE_CLASS = /^(PreviewImage|PreviewAny|PreviewMask|Note|MarkdownNote|XB_CanvasLabel|PlaySound|DisplayAny|ShowText)/i

const IMAGE_LOAD = /^(LoadImage|ETN_LoadImageBase64|LoadImageOutput|LoadImageMask)\b/i
const VIDEO_LOAD = /LoadVideo|VHS_LoadVideo|LoadVideoFromPath|VideoInput/i
const AUDIO_LOAD = /^(LoadAudio|VHS_LoadAudio|LoadAudioPath)\b/i
const IMAGE_SAVE = /^(SaveImage)\b/i
const VIDEO_SAVE = /VHS_VideoCombine|SaveVideo|CreateVideo|SaveWEBM|VideoCombine/i
const AUDIO_SAVE = /VAEDecodeAudio|SaveAudio|SaveAudioMP3|SaveAudioOpus/i
const LORA_CLASS = /^(LoraLoader|LoraLoaderModelOnly)$/
const VIDEO_HINT = /video|vhs_|animatediff|svd|wanvideo|minimax|hailuo|hunyuanvideo|ltxvideo|mochi|cogvideo|wanimage|i2v|t2v|image.?to.?video|text.?to.?video/i
const UPSCALE = /Upscale|UltimateSDUpscale|ImageUpscale/i

/**
 * Offline official-node fallback (generated by scripts/update-official-nodes.mjs
 * from a live server's python_module tags). Live classification at import /
 * generate time always wins; this only serves offline previews.
 */
let OFFICIAL_FALLBACK = null
function officialFallback() {
  if (OFFICIAL_FALLBACK) return OFFICIAL_FALLBACK
  try {
    const p = path.join(path.dirname(fileURLToPath(import.meta.url)), 'official-nodes.json')
    OFFICIAL_FALLBACK = new Set(JSON.parse(fs.readFileSync(p, 'utf8')).official)
  } catch {
    OFFICIAL_FALLBACK = new Set()
  }
  return OFFICIAL_FALLBACK
}

function isLink(v) {
  return Array.isArray(v) && v.length >= 2 && (typeof v[0] === 'string' || typeof v[0] === 'number')
}

function titleOf(node) {
  return String(node?._meta?.title || '')
}

function entries(graph) {
  return Object.entries(graph || {}).filter(([, n]) => n && n.class_type)
}

export function assertApiGraph(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw Object.assign(new Error('Not a JSON object'), { code: 'BAD_WORKFLOW' })
  }
  if (Array.isArray(raw.nodes) && (raw.links || raw.last_node_id != null)) {
    throw Object.assign(new Error('这是 ComfyUI 界面格式。请在 ComfyUI 打开 → Enable Dev mode Options → Save (API Format)。'), { code: 'UI_FORMAT' })
  }
  const nodes = entries(raw)
  if (!nodes.length) {
    throw Object.assign(new Error('No class_type nodes (need API format JSON)'), { code: 'BAD_WORKFLOW' })
  }
  return raw
}

function consumers(graph, nodeId) {
  const id = String(nodeId)
  const hits = []
  for (const [cid, n] of entries(graph)) {
    for (const [field, val] of Object.entries(n.inputs || {})) {
      if (isLink(val) && String(val[0]) === id) hits.push({ node: cid, field, class_type: n.class_type })
    }
  }
  return hits
}

function scalarTextField(node) {
  const ins = node.inputs || {}
  for (const f of ['string', 'value', 'text', 'prompt']) {
    if (typeof ins[f] === 'string') return f
  }
  return null
}

function looksTemplate(text) {
  return /\[prompt\]/i.test(String(text || ''))
}

function classifyMedia(graph, officialSet) {
  let imageIn = false
  let videoIn = false
  let audioIn = false
  let imageOut = false
  let videoOut = false
  let audioOut = false
  let emptyLatent = false
  let upscale = false
  const custom = new Set()
  const classes = []
  const known = officialSet || officialFallback()

  for (const [, n] of entries(graph)) {
    const c = n.class_type
    classes.push(c)
    if (IGNORE_CLASS.test(c)) continue
    if (IMAGE_LOAD.test(c)) imageIn = true
    if (VIDEO_LOAD.test(c)) videoIn = true
    if (AUDIO_LOAD.test(c)) audioIn = true
    if (IMAGE_SAVE.test(c)) imageOut = true
    if (VIDEO_SAVE.test(c)) videoOut = true
    if (AUDIO_SAVE.test(c) || /audio/i.test(c) && /decode|save/i.test(c)) audioOut = true
    if (/^EmptyLatentImage/i.test(c)) emptyLatent = true
    if (UPSCALE.test(c)) upscale = true
    if (VIDEO_HINT.test(c)) videoOut = videoOut || VIDEO_SAVE.test(c) || /combine|save|decode/i.test(c)
    if (!known.has(c)) {
      if (!IGNORE_CLASS.test(c)) custom.add(c)
    }
  }

  // Class names lie: MiniMaxH3ImageToVideo in this graph has no image input.
  const mode = []
  if (videoOut && imageIn) mode.push('i2v')
  else if (videoOut) mode.push('t2v')
  if (!videoOut && imageOut && imageIn) mode.push('i2i')
  if (!videoOut && imageOut && !imageIn) mode.push('t2i')
  if (!mode.length && emptyLatent && imageOut) mode.push('t2i')
  if (!mode.length && videoOut) mode.push('t2v')

  const inn = []
  const out = []
  if (imageIn) inn.push('image')
  if (videoIn) inn.push('video')
  if (audioIn) inn.push('audio')
  inn.push('text')
  if (videoOut) out.push('video')
  else if (imageOut) out.push('image')
  if (audioOut) out.push('audio')
  if (!out.length && videoOut) out.push('video')

  return {
    mode,
    media: { in: [...new Set(inn)], out: [...new Set(out)] },
    imageIn,
    videoIn,
    audioIn,
    imageOut,
    videoOut,
    audioOut,
    upscale,
    custom: [...custom].sort(),
    classes,
  }
}

function pickPromptSlots(graph) {
  const candidates = []
  for (const [id, n] of entries(graph)) {
    if (IGNORE_CLASS.test(n.class_type)) continue
    const field = scalarTextField(n)
    if (!field) continue
    const text = n.inputs[field]
    const title = titleOf(n)
    const cons = consumers(graph, id)
    let score = 0
    if (/负面|negative/i.test(title)) score -= 200
    if (/正面|positive/i.test(title) || (/提示词/.test(title) && !/负/.test(title))) score += 80
    if (cons.some((c) => /^(prompt|positive|text)$/i.test(c.field))) score += 50
    if (cons.some((c) => VIDEO_HINT.test(c.class_type))) score += 25
    if (/PrimitiveStringMultiline|Simple String|CLIPTextEncode/i.test(n.class_type)) score += 10
    if (looksTemplate(text)) score -= 120
    if (/宽度|高度|width|height|强度|turbo|seed|cfg/i.test(title)) score -= 80
    score += Math.min(25, Math.floor(String(text).length / 80))
    candidates.push({ id, field, title, text, score, cons })
  }
  const prompt = candidates.filter((c) => c.score > 0).sort((a, b) => b.score - a.score)[0]
    || candidates.filter((c) => !/负面|negative/i.test(c.title)).sort((a, b) => b.score - a.score)[0]
  const negative = candidates.filter((c) => /负面|negative/i.test(c.title) || c.cons.some((x) => /negative/i.test(x.field)))
    .sort((a, b) => a.score - b.score)[0]
  return { prompt, negative }
}

function keyFromTitle(title, fallback) {
  const t = title || ''
  if (/负面|negative/i.test(t)) return 'negative'
  if (/正面|positive/i.test(t) || (/提示词/.test(t) && !/负/.test(t))) return 'prompt'
  if (/宽度|width/i.test(t)) return 'width'
  if (/高度|height/i.test(t)) return 'height'
  if (/turbo/i.test(t) && /强度|strength/i.test(t)) return 'turbo_strength'
  if (/pixel|千像素|pixel_k/i.test(t)) return 'pixel_k'
  if (/seed/i.test(t)) return 'seed'
  return fallback
}

function addSlot(slots, key, spec) {
  if (!key || slots[key]) return
  slots[key] = { key, ...spec }
}

function numberish(v) {
  return typeof v === 'number' || (typeof v === 'string' && v !== '' && Number.isFinite(Number(v)))
}

function paramSlots(graph, slots) {
  const PARAM_FIELDS = [
    ['duration', 'number', 'duration'],
    ['fps', 'number', 'fps'],
    ['frame_rate', 'number', 'fps'],
    ['aspect_ratio', 'text', 'aspect'],
    ['megapixels', 'number', null],
    ['frames', 'number', 'duration'],
    ['length', 'number', 'duration'],
    ['width', 'number', 'size'],
    ['height', 'number', 'size'],
  ]
  for (const [id, n] of entries(graph)) {
    if (IGNORE_CLASS.test(n.class_type)) continue
    const ins = n.inputs || {}
    const isParamNode = /VideoParams|H3Video|EmptyLatentImage|VHS_VideoCombine/i.test(n.class_type)
    for (const [field, type, can] of PARAM_FIELDS) {
      if (!(field in ins) || isLink(ins[field])) continue
      if (type === 'number' && !numberish(ins[field])) continue
      if (type === 'text' && typeof ins[field] !== 'string') continue
      if (!isParamNode && !/duration|fps|aspect|megapixel|width|height/i.test(field)) continue
      if (!isParamNode && !/VideoParams|EmptyLatent|Hailuo/i.test(n.class_type) && !['width', 'height'].includes(field)) continue
      let key = field === 'frame_rate' ? 'fps' : field
      if (key === 'length' && slots.duration) continue
      if (key === 'fps' && slots.fps) continue
      if (['width', 'height'].includes(key) && isLink(ins[key])) continue
      addSlot(slots, key, {
        type,
        required: false,
        node: String(id),
        field,
        as_string: typeof ins[field] === 'string',
      })
    }
  }
}

function samplerSlots(graph, slots) {
  for (const [id, n] of entries(graph)) {
    const ins = n.inputs || {}
    for (const field of ['steps', 'cfg', 'denoise']) {
      if (slots[field]) continue
      if (field in ins && !isLink(ins[field]) && numberish(ins[field])) {
        addSlot(slots, field, { type: 'number', required: false, node: String(id), field })
      }
    }
    if (!slots.seed) {
      for (const field of ['seed', 'noise_seed']) {
        if (field in ins && !isLink(ins[field])) {
          addSlot(slots, 'seed', { type: 'seed', required: false, node: String(id), field })
          break
        }
      }
    }
  }
}

function stringNumberSlots(graph, slots) {
  for (const [id, n] of entries(graph)) {
    if (!/Simple String/i.test(n.class_type)) continue
    const title = titleOf(n)
    const field = scalarTextField(n)
    if (!field) continue
    const key = keyFromTitle(title, null)
    if (!key || key === 'prompt' || key === 'negative') continue
    if (slots[key]) continue
    addSlot(slots, key, {
      type: numberish(n.inputs[field]) ? 'number' : 'text',
      required: false,
      node: String(id),
      field,
      as_string: true,
    })
  }
}

function mediaSlots(graph, slots, kind) {
  const re = kind === 'image' ? IMAGE_LOAD : kind === 'video' ? VIDEO_LOAD : AUDIO_LOAD
  const fields = kind === 'image' ? ['image', 'base64'] : kind === 'video' ? ['video', 'file', 'filename'] : ['audio', 'file', 'filename']
  for (const [id, n] of entries(graph)) {
    if (!re.test(n.class_type)) continue
    const ins = n.inputs || {}
    let field = fields.find((f) => f in ins)
    if (!field) field = kind === 'image' && /base64/i.test(n.class_type) ? 'image' : fields[0]
    addSlot(slots, kind, {
      type: kind,
      required: true,
      node: String(id),
      field,
    })
    break
  }
}

function loraPits(graph) {
  const loras = []
  let i = 0
  for (const [id, n] of entries(graph)) {
    if (!LORA_CLASS.test(n.class_type)) continue
    const name = typeof n.inputs?.lora_name === 'string' ? n.inputs.lora_name : ''
    const modelOnly = n.class_type === 'LoraLoaderModelOnly'
    const key = i === 0 ? 'quality' : i === 1 ? 'speed' : `lora_${i + 1}`
    const spec = {
      key,
      role: i === 0 ? 'quality' : i === 1 ? 'speed' : 'extra',
      node: String(id),
      nameField: 'lora_name',
      default_name: name || undefined,
      vacant: !name,
    }
    if (modelOnly && isLink(n.inputs?.strength_model)) {
      /* strength lives on another node; leave strengthField on this node if scalar */
    } else if (n.inputs?.strength_model != null && !isLink(n.inputs.strength_model)) {
      spec.strengthField = 'strength_model'
      if (n.inputs?.strength_clip != null && !isLink(n.inputs.strength_clip)) spec.clipStrengthField = 'strength_clip'
    }
    loras.push(spec)
    i += 1
  }
  return loras
}

function modelRefs(graph) {
  const models = {}
  const vaes = []
  for (const [id, n] of entries(graph)) {
    if (n.class_type === 'UNETLoader' && typeof n.inputs?.unet_name === 'string' && !models.unet) {
      models.unet = { key: 'unet', node: String(id), field: 'unet_name' }
    }
    if (n.class_type === 'CLIPLoader' && typeof n.inputs?.clip_name === 'string' && !models.clip) {
      models.clip = { key: 'clip', node: String(id), field: 'clip_name' }
      if (n.inputs?.type != null && !isLink(n.inputs.type)) {
        models.clip_type = { key: 'clip_type', node: String(id), field: 'type' }
      }
    }
    if (n.class_type === 'VAELoader' && typeof n.inputs?.vae_name === 'string') {
      vaes.push({ id, name: n.inputs.vae_name, cons: consumers(graph, id) })
    }
  }
  if (vaes.length === 1) {
    models.vae = { key: 'vae', node: String(vaes[0].id), field: 'vae_name' }
  } else if (vaes.length > 1) {
    const audio = vaes.find((v) => /audio/i.test(v.name) || v.cons.some((c) => /audio/i.test(c.class_type)))
    const video = vaes.find((v) => v !== audio)
    if (video) models.vae = { key: 'vae', node: String(video.id), field: 'vae_name' }
    if (audio) models.vae_audio = { key: 'vae_audio', node: String(audio.id), field: 'vae_name' }
  }
  return models
}

function canvasTitle(graph, fallback) {
  for (const [, n] of entries(graph)) {
    const t = titleOf(n)
    if (n.class_type === 'XB_CanvasLabel' && t && !/教程|搜/.test(t)) return t
  }
  return fallback
}

function suggestId(graph, fileBase, mode) {
  const blob = entries(graph).map(([, n]) => `${n.class_type} ${titleOf(n)} ${n.inputs?.unet_name || ''}`).join(' ')
  const m = mode[0] || 'workflow'
  if (/minimax/i.test(blob)) return `minimax-h3-${m}`
  const slug = String(fileBase || 'workflow')
    .replace(/\.json$/i, '')
    .replace(/[（(][^）)]*[）)]/g, '')
    .replace(/[^\w\u4e00-\u9fff]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)
    .toLowerCase()
  return slug || `workflow-${m}`
}

function promptStyleOf(text, mode) {
  const t = String(text || '')
  const video = mode.includes('t2v') || mode.includes('i2v')
  if (/[\u4e00-\u9fff]/.test(t) && video) {
    return {
      prompt_style: 'natural',
      prompt_hint: 'Natural-language shot list (who/where/camera). Optional timestamps. This is video, not danbooru tags, not a still image.',
    }
  }
  if (video) {
    return {
      prompt_style: 'natural_en',
      prompt_hint: 'Full sentences of motion and camera. Outputs video, not a still. Do not use 1girl tags unless the graph is anime-still.',
    }
  }
  return {
    prompt_style: 'natural_en',
    prompt_hint: 'Follow the template. Do not claim capabilities listed in cannot.',
  }
}

function capabilitiesOf(info, slots, loras) {
  const can = []
  const cannot = []
  if (slots.prompt) can.push('prompt')
  if (loras.length) can.push('lora_switch')
  else cannot.push('lora_switch')
  if (slots.width || slots.height) can.push('size')
  if (slots.megapixels) can.push('resolution')
  if (slots.seed) can.push('seed')
  if (slots.duration || slots.frames || slots.length) can.push('duration')
  if (slots.fps) can.push('fps')
  if (slots.aspect_ratio) can.push('aspect')
  if (info.videoOut) can.push('video')
  if (info.audioOut) can.push('audio')
  if (info.imageIn) can.push('image_input')
  if (info.videoIn) can.push('video_input')

  const mode = info.mode
  const all = ['t2i', 'i2i', 't2v', 'i2v', 'upscale', 'logo']
  for (const m of all) {
    if (!mode.includes(m)) cannot.push(m)
  }
  if (!info.upscale && !cannot.includes('upscale')) cannot.push('upscale')
  if (!info.imageIn && !cannot.includes('image_input')) cannot.push('image_input')
  return { mode, can: [...new Set(can)], cannot: [...new Set(cannot)] }
}

function warningsOf(info, graph, slots, liveClassified) {
  const w = []
  if (info.mode.includes('t2v') && /ImageToVideo/i.test(info.classes.join(' '))) {
    w.push('A node is named ImageToVideo but no LoadImage is wired — treated as text-to-video, not i2v.')
  }
  if (info.videoOut) w.push('Output is video (VHS/SaveVideo), not SaveImage. Do not promise a still.')
  if (info.audioOut) w.push('Graph also decodes audio into the video combine.')
  if (info.custom.length) {
    const suffix = liveClassified
      ? ' (verified against the live server)'
      : ' (offline scan; live preflight is authoritative)'
    w.push(`Custom nodes required: ${info.custom.slice(0, 12).join(', ')}${suffix}`)
  }
  if (!slots.prompt) w.push('Could not auto-detect a prompt slot; inspect the graph in ComfyUI and edit the contract.')
  if (info.mode.includes('t2v') || info.mode.includes('i2v')) {
    w.push('Video jobs need VRAM and custom nodes. If preflight reports NODE_MISSING / MODEL_MISSING, say the machine cannot run this template — do not fake an image.')
  }
  return w
}

export function scanGraph(raw, opts = {}) {
  const graph = assertApiGraph(raw)
  const liveClassified = opts.officialClasses instanceof Set
  const info = classifyMedia(graph, liveClassified ? opts.officialClasses : null)
  const slots = {}
  const { prompt, negative } = pickPromptSlots(graph)
  if (prompt) {
    addSlot(slots, 'prompt', {
      type: 'text',
      required: true,
      node: String(prompt.id),
      field: prompt.field,
    })
  }
  if (negative && String(negative.id) !== String(prompt?.id)) {
    addSlot(slots, 'negative', {
      type: 'text',
      required: false,
      node: String(negative.id),
      field: negative.field,
    })
  }
  if (info.imageIn) mediaSlots(graph, slots, 'image')
  if (info.videoIn) mediaSlots(graph, slots, 'video')
  if (info.audioIn) mediaSlots(graph, slots, 'audio')
  paramSlots(graph, slots)
  stringNumberSlots(graph, slots)
  samplerSlots(graph, slots)

  const loras = loraPits(graph)
  const models = modelRefs(graph)
  const fileBase = opts.fileBase || ''
  const id = String(opts.id || suggestId(graph, fileBase, info.mode)).trim()
  const title = String(opts.title || canvasTitle(graph, fileBase.replace(/\.json$/i, '') || id)).trim()
  const style = promptStyleOf(prompt?.text, info.mode)
  const capabilities = capabilitiesOf(info, slots, loras)
  const warnings = warningsOf(info, graph, slots, liveClassified)

  const notes = warnings.join(' ')

  const contract = {
    id,
    title,
    workflow: `${id}.json`,
    prompt_style: style.prompt_style,
    prompt_hint: style.prompt_hint,
    media: info.media,
    capabilities: { ...capabilities, style: [] },
    slots,
    loras,
    models,
    warnings,
    notes,
  }

  for (const s of Object.values(slots)) {
    delete s.can
    if (!s.as_string) delete s.as_string
    if (!SLOT_TYPES.has(s.type)) s.type = 'text'
  }

  return {
    ok: true,
    format: 'api',
    node_count: entries(graph).length,
    class_types: [...new Set(info.classes)].sort(),
    contract,
    summary: summarizeDraft(contract),
  }
}

export function summarizeDraft(c) {
  const slots = c.slots || {}
  return {
    id: c.id,
    title: c.title,
    media: c.media,
    mode: c.capabilities?.mode || [],
    can: c.capabilities?.can || [],
    cannot: c.capabilities?.cannot || [],
    required_slots: Object.values(slots).filter((s) => s.required).map((s) => s.key),
    optional_slots: Object.values(slots).filter((s) => !s.required).map((s) => s.key),
    lora_slots: (c.loras || []).map((l) => l.key),
    warnings: c.warnings || [],
    prompt_style: c.prompt_style,
  }
}

export { SLOT_TYPES }
